apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
  - name: vprocache01
    protocol: TCP
    port: 11211
    targetPort: vpromc-port
  selector:
    app: vpromc
  type: ClusterIP
