apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp-service
  type: LoadBalancer
  ports:
  - name: vproapp-service
    protocol: TCP
    port: 80
    targetPort: vproapp-port
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
# you can specify a value in the `spec.ports[*].nodePort` field.
